# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zTifR9CvF5M5ZS9ab7eHda6HKdJ7HNAf

EX:1
"""

a=int(input("enter a: " ))
b=int(input("enter b: "))

sum=a+b
mul=a*b

if(mul>1000):
    print(sum)
    
else:

   print(mul)

"""EX:2"""

r=float(input("enter radious: "))

ans=3.1416*r**2

print(ans)
print(2*3.1416*r)

"""EX:3"""

p=int(input("enter p: "))
r=int(input("enter r: "))
t=int(input("enter t: "))

a=p*(1+r/100)**t

print(a)

"""EX:4"""

n=int(input("enter n: "))

ans=n*(n + 1)*(2*n + 1)

ans=ans/6

print(ans)

"""EX:5"""

def prime_find_2018_2_60_061(n,b):
 b=True
 
 for i in range(2, n-2,1 ):
     if(n%i==0):
      b=False
      print("no")
      break    

 if(b):
  print("yes")

n=int(input("enter n: "))

#b=True

prime_find_2018_2_60_061(n,True)

"""EX:6"""

a = [0, 1]

def fib(n):
	if n<0:
		print("negative number is not allowed")
	elif n<= len(a):
		return a[n-1]
	else:
		sum = fib(n-1)+fib(n-2)
		a.append(sum)
		return sum

n=int(input("enter n: "))

print(fib(n))

"""EX:7"""

a=[1,2,3,4,5]

sum=0

def summation(sum):
 
        for i in range (0,len(a),1):
            sum+=a[i]
    
        return sum

print( summation(sum) )

"""EX:8"""

a=[1,2,3,4,5]

sum=0

def summation(sum):
 
        for i in range (0,len(a),1):
            if(i%2==0):
             sum+=a[i]
    
        return sum

print( summation(sum) )

"""EX:9"""

a=[]

n=int(input())

for i in range (0,n,1):
        a.append(int(input()))
        

maximum=a[0]
minimum=a[0]

def max_2018_2_60_102(maximum):
    
    for i in range (0,len(a),1):
      if(a[i]>maximum):
          maximum=a[i]

    return maximum

def min_2018_2_60_102(mainimum):
    
    for i in range (0,len(a),1):
       if(mainimum>a[i]):
           mainimum=a[i]
           
    return mainimum

print( max_2018_2_60_102(maximum) )

print(min_2018_2_60_102(minimum))

"""EX:10

"""

a=[2,1,5,4,3]

x=sorted(a)

print(x[len(a)-2])

"""EX:11"""

s=input("enter s: ")

for i in range (0,len(s),1):
    if(i%2==0):
        print(s[i])

"""EX:12"""

def rem(s,n):
    
   list=[]
    
   for i in range(n,len(s),1):
       list.append(s[i])
             
   return list

s=input()
n=int(input())

print( rem(s,n) )

"""EX:14"""

def palindrome_checker_2018_2_60_061(s,n):
    
   for i in range (0,(int(len(s)/2)),1):
        if(s[i]!=s[n-i-1]):
            return False
                   
                        
   return True

s=input()

print(palindrome_checker_2018_2_60_061(s,len(s)))

"""EX:15"""

list1=[1,2,3,4,5,6]
list2=[7,8,9,10,11,12]
   
a=[]
b=[]

n=len(list1)

for i in range (0,n,1):
    if(list1[i]%2==0):
        a.append(list1[i])
    if(list2[i]%2==1):
        b.append(list2[i])
        
        
print(a)
print(b)