# -*- coding: utf-8 -*-
"""LAB2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z9_eJRXg9bIxKM3F-aaQ4Yzjr1po2ULL
"""



"""EX:1"""

numbers = [i for i in range(1,1001)]
find_all_the_numbers = [n for n in numbers if n % 8 == 0]
print(find_all_the_numbers)

"""EX:2"""

numbers = [i for i in range(1,1001)]
numbers_having_6 = [n for n in numbers if "6" in str(n)]
print(numbers_having_6)

"""EX:3"""

string = "Practice Problems to Drill List Comprehension in Your Head."
q3_answer = len([char for char in string if char == " "])
print(q3_answer)

"""EX:4"""

string = "Practice Problems to Drill List Comprehension in Your Head."
q4_answer = "".join([char for char in string if char not in ["a","e","i","o","u"]])
print(q4_answer)

"""EX:5"""

string = "Practice Problems to Drill List Comprehension in Your Head. "
words = string.split(" ")
q5_answer = [word for word in words if len(word) < 5]
print(q5_answer)

"""EX:6"""

words = "Practice Problems to Drill List Comprehension in Your Head."
q6_answer = {word:len(word) for word in words}
print(q6_answer)

"""EX:7"""

nums = [i for i in range(1,1001)]
q7_answer = [num for num in nums if True in [True for divisor in range(2,10) if num % divisor == 0]]
print(q7_answer)

"""EX:8"""

nums = [i for i in range(1,1001)]
q8_answer = {num:max([divisor for divisor in range(1,10) if num % divisor == 0]) for num in nums}
print(q8_answer)